### PR TITLE
Add sample github actions config

### LINKED ISSUE #192: Migrate from TravisCI to GitHub Actions
### What is the feature?

I'd like to suggest moving to GitHub Actions for our CI workflow and moving away from our current TravisCI implementation.

I'd definitely like to get other opinions on this.

### What benefits will this change bring?

This will allow us to keep all our workflow for the SDK on GitHub.

We could leverage a lot of the prebuilt workflows, maintaining functionality from our existing pipelines and adding additional functionality too.

### Additional context

From what I've read about GitHub Actions and my limited exposure to them, it shouldn't be too hard to migrate our Travis config over.

### PR DESCRIPTION
**Pull request by tylerwoonton**
Fixes #192 

If we want to migrate from TravisCI to GitHub Actions, this config would give us the same functionality.

### CODE REVIEW

**Comment by tylerwoonton** [comment]
@gavtaylor there's a sample config for actions here but as it's not my repo, I don't think I can enable the tests to run... I got them working correctly on my fork and the output looks quite nice.

Screenshot 2020-02-03 at 20 29 50

**Comment by tylerwoonton** [comment]
Only thing we'll definitely want to look into is who gets notifications. When I had failing configs on my fork, it sent me an email for each job failure.

**Comment by MisterCoder** [comment]
LGTM

**Comment by gavtaylor** [comment]
@tylerwoonton apologies for this, its been a bit forgotten about. it looks ok to me but could you give it a quick once over when you have a sec, make sure you're still happy with it and if you are, lets get it merged in

**Comment by tylerwoonton** [comment]
@gavtaylor I've made a tweak to allow it to run on pull requests, pushes to master, and a cron.

I'm happy with this. If you are, let's get it merged. I can't remember if you have to enable actions on the repo but the actions tab should have more info.

**Comment by gavtaylor** [comment]
> @gavtaylor I've made a tweak to allow it to run on pull requests, pushes to master, and a cron.
> 
> I'm happy with this. If you are, let's get it merged. I can't remember if you have to enable actions on the repo but the actions tab should have more info.

yep actions are enabled, lets get this merged :+1:

**Pull request merged**
